<?php
/**
 * Created by PhpStorm.
 * User: hantong
 * Date: 16/10/24
 * Time: 下午4:57
 */

return [
	'DBHelperi'                             => INCLUDE_DIR . "DBHelperi.class.php",
	'DBHelperi_huanpeng'                    => INCLUDE_DIR . "DBHelperi_huanpeng.class.php",
	'RedisHelp'                             => INCLUDE_DIR . "redis.class.php",
	'PickBean'                              => INCLUDE_DIR . "PickBean.class.php",
	'RankUpdate'                            => INCLUDE_DIR . "LRRank.class.php",
	'hp\lib\Live'                           => INCLUDE_DIR . "lib/Live.class.php",
	'hp\lib\CDNHelper'                      => INCLUDE_DIR . "lib/CDNHelper.class.php",
	'hp\lib\WcsHelper'                      => INCLUDE_DIR . "lib/WcsHelper.class.php",
	'hp\lib\Video'                          => INCLUDE_DIR . "lib/Video.class.php",
	'hp\lib\Anchor'                         => INCLUDE_DIR . "lib/Anchor.class.php",
	'hp\lib\User'                           => INCLUDE_DIR . "lib/User.class.php",
	'hp\lib\Rank'                           => INCLUDE_DIR . "lib/Rank.class.php",
	'hp\lib\BaseInfo'                       => INCLUDE_DIR . "lib/BaseInfo.class.php",
	'hp\lib\Game'                           => INCLUDE_DIR . "lib/Game.class.php",
	'hp\lib\Gift'                           => INCLUDE_DIR . "lib/Gift.class.php",
	'hp\lib\Register'                       => INCLUDE_DIR . "lib/Register.class.php",
	'hp\lib\Task'                           => INCLUDE_DIR . "lib/Task.class.php",
	'hp\lib\SocketSend'                     => INCLUDE_DIR . "lib/SocketSend.class.php",
	'hp\lib\MsgPackage'                     => INCLUDE_DIR . "lib/MsgPackage.class.php",
	'hp\lib\LiveRoom'                       => INCLUDE_DIR . "lib/LiveRoom.class.php",
	'hp\lib\RoomRank'                       => INCLUDE_DIR . "lib/RoomRank.class.php",
	'hp\lib\RedEnvelope'                    => INCLUDE_DIR . "lib/RedEnvelope.class.php",
	'hp\lib\RoomTimerGetBean'               => INCLUDE_DIR . "lib/RoomTimerGetBean.class.php",
	'hp\lib\TreasureBox'                    => INCLUDE_DIR . "lib/TreasureBox.class.php",
	'hp\lib\Finance'                        => INCLUDE_DIR . "lib/finance.class.php",
	'hp\lib\FinanceError'                   => INCLUDE_DIR . "lib/financeError.class.php",
	'hp\lib\FinanceBase'                    => INCLUDE_DIR . "lib/FinanceBase.class.php",
	'hp\lib\FinanceStatistic'               => INCLUDE_DIR . "lib/FinanceStatistic.class.php",
	'hp\lib\SmsSend'                        => INCLUDE_DIR . "lib/SmsSend.class.php",
	'hp\lib\SmsBiz'                         => INCLUDE_DIR . "lib/SmsBiz.class.php",
	'hp\lib\MailSend'                       => INCLUDE_DIR . "lib/MailSend.class.php",
	'hp\lib\MailBiz'                        => INCLUDE_DIR . 'lib/MailBiz.class.php',
	'hp\lib\SiteMsgBiz'                     => INCLUDE_DIR . "lib/SiteMsgBiz.class.php",
	'hp\lib\LivePush'                       => INCLUDE_DIR . "lib/LivePush.class.php",
	'hp\lib\ApplePush'                      => INCLUDE_DIR . "lib/ApplePush.class.php",
	'hp\lib\LiveActivity'                   => INCLUDE_DIR . "lib/LiveActivity.class.php",
	'hp\lib\RedisCacheManage'               => INCLUDE_DIR . "lib/RedisCacheManage.class.php",
	'hp\service\rank\RankService'           => INCLUDE_DIR . "service/rank/RankService.class.php",
	'hp\service\rank\LiveRoomRankService'   => INCLUDE_DIR . "service/rank/LiveRoomRankService.class.php",
	'hp\service\game\GameService'           => INCLUDE_DIR . "service/game/GameService.class.php",
	'hp\service\live\LiveService'           => INCLUDE_DIR . "service/live/LiveService.class.php",
	'hp\service\live\VideoService'          => INCLUDE_DIR . "service/live/VideoService.class.php",
	'hp\service\room\RoomInitService'       => INCLUDE_DIR . "service/room/RoomInitService.class.php",
	'hp\service\room\LiveRoomService'       => INCLUDE_DIR . "service/room/LiveRoomService.class.php",
	'hp\service\gift\GiftService'           => INCLUDE_DIR . "service/gift/GiftService.class.php",
	'hp\service\room\RoomManagerService'    => INCLUDE_DIR . "service/room/RoomManagerService.class.php",
	'hp\service\anchor\AnchorDataService'   => INCLUDE_DIR . "service/anchor/AnchorDataService.class.php",
	'hp\service\anchor\AnchorNoticeService' => INCLUDE_DIR . "service/anchor/AnchorNoticeService.class.php",
	'hp\service\cookie\CookieService'       => INCLUDE_DIR . "service/cookie/CookieService.class.php",
	'hp\service\user\UserDataService'       => INCLUDE_DIR . "service/user/UserDataService.class.php",
	'hp\service\user\FollowService'         => INCLUDE_DIR . "service/user/FollowService.class.php",
	'hp\service\user\UserRegisterService'   => INCLUDE_DIR . "service/user/UserRegisterService.class.php",
	'hp\service\home\IndexService'          => INCLUDE_DIR . "service/home/IndexService.class.php",
	'hp\service\home\HeaderService'         => INCLUDE_DIR . "service/home/HeaderService.class.php",
	'hp\service\task\TaskService'           => INCLUDE_DIR . "service/task/TaskService.class.php",
	'hp\service\task\TreasureService'       => INCLUDE_DIR . "service/task/TreasureService.class.php",
	'hp\service\common\PcHeader'            => INCLUDE_DIR . "service/common/PcHeader.class.php",
	'hp\service\common\PcCommon'            => INCLUDE_DIR . "service/common/PcCommon.class.php",
	'hp\service\payment\UnifiedOrder'       => INCLUDE_DIR . 'service/payment/UnifiedOrder.class.php',
	'hp\service\payment\Alipay'             => INCLUDE_DIR . "service/payment/Alipay.class.php",
	'hp\service\payment\WxpayHP'            => INCLUDE_DIR . "service/payment/WxpayHP.class.php",
	'hp\service\payment\WxpayUnified'       => INCLUDE_DIR . "service/payment/WxpayUnified.class.php",
];